### PR TITLE
fix(CLI): ensure new command runs npm install

### LINKED ISSUE #550: Fractal new fails after trying to install NPM dependencies
Have you read Fractal's [Code of Conduct](/.github/CODE_OF_CONDUCT.md)? By filing an Issue, you are expected to comply with it, including treating everyone with respect

Do you want to ask a question? Are you looking for support? The Fractal Discord server is the best place for getting support:
https://discord.gg/vuRz4Yx

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

I've had no issues installing fractal projects in the past, but `fractal new [projectname]` seems to crash after beginning to install NPM dependencies.

Thanks for your help

### Steps to Reproduce

1. Install most recent version of fractal globally with `npm i -g @frctl/fractal`
2. Create folder for project
3. CD into project directory and un `fractal new test-project`

**Expected behavior:** A new fractal project is created with boilerplate structure

**Actual behavior:** Installation begins and fails in this way:
```
? Will you use Git for version control on this project? Yes
Generating project structure...
Installing NPM dependencies - this may take some time!
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Reproduces how often:** 100%

### Versions

* What version of Fractal are you running? (run `npm list @frctl/fractal` / `yarn list @frctl/fractal`
this is the response when running `npm list...`:
`-- (empty)`
however, when I run fractal -v, I get the following response: ```
│ Fractal CLI                                                  │
│──────────────────────────────────────────────────────────────│
│ No local Fractal configuration found.                        │
│ You can use the fractal new command to create a new project. │
│──────────────────────────────────────────────────────────────│
│ Powered by Fractal v1.2.1          
```
* What version of Node.js are you running? (run `node -v`)
v10.16.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### PR DESCRIPTION
**Pull request by LeBenLeBen**
Fixes #550 

I decided to open a PR because it works like that but I have no clue if this is actually a good solution 😂 

@Chapabu would definitely need your input on that, apparently you worked on this part when removing shelljs a while ago.

### CODE REVIEW

**Comment by Chapabu** [comment]
In principle I'm good with this. HOWEVER I can't test it on Windows to see if it resolved the underlying issue. I don't suppose you've been able to have you?

**Comment by risker** [comment]
Tried this out on Windows:
- cmd freezes at "Installing npm dependencies"
- Powershell freezes too at the same spot
- git bash errors out with `✘ TypeError: Cannot read property 'toString' of null`

**Comment by LeBenLeBen** [comment]
Damn, thanks for having a look and testing. Unfortunately I don't have neither a Windows setup nor the knowledge to test it. I guess I'll let somebody else tackle this issue. Feel free to close the MR if you think the solution is not usable at all, I won't get mad 😜

**Comment by risker** [comment]
Could we try moving from spawn back to exec? I believe that was used previously before the breaking update.

**Comment by Chapabu** [comment]
Yeoman uses https://github.com/sindresorhus/execa/ which looks quite good, maybe try swapping to that?

**Comment by LeBenLeBen** [comment]
@Chapabu Yeah that seems to be a common library for such usage, Vue CLI use execa as well. I've changed the code in this direction and cleaned up what ended up being unused. It works fine on MacOS.

Can somebody test on Windows?

**Comment by risker** [comment]
Works on Windows in Git Bash only. Both cmd and PowerShell freeze and die after `Generating project structure...`. I have no idea why...

**Pull request merged**
