### PR TITLE
Remove mergeProp's ability to merge arrays

### PR DESCRIPTION
**Pull request by matijs**
Solves #123
Update test accordingly

### CODE REVIEW

**Comment by matijs** [comment]
In a rudimentary test this seems to solve the issue I had, I'm not sure if other things broke or if this is covered by tests.

**Comment by allmarkedup** [comment]
Thanks @matijs - I'm actually just putting together a 1.1 release that should fix the array merging issue in the context data. However I'm still actually undecided if I want to change this behaviour in `mergeProp` itself because it is responsible for handling other situations as well in which the array merge may be the correct route to take. I'll leave this open until I make a firm decision but tbh I'll probably leave it as is for now.

**Comment by matijs** [comment]
That's cool. Context data seems to be where this belongs anyway :)

**Comment by dkhuntrods** [comment]
This is resolved by the upcoming 1.1 release - array merging issues are fixed within the context data.

**Comment by sun** [comment]
Merging array subkeys made perfect sense for us. Would it make sense to turn this into a configuration setting instead of hardcoding one behavior or the other?

**Pull request closed without merging**
