### PR TITLE
Remove ShellJS dependency.

### LINKED ISSUE #437: Fractal shellJS vulnerability
## Background:
- FEC pattern library (https://fec-pattern-library.app.cloud.gov/) is a public site used by the FEC to catalog our style components which is built with [Fractal](https://github.com/frctl/fractal)

- Our vulnerability tracker, Snyk, flagged a [high severity command injection vulnerability](https://snyk.io/vuln/npm:shelljs:20140723) with Fractal that we can’t patch ourselves. Here is also a link to our fec-pattern-library issue for more context: https://github.com/fecgov/fec-pattern-library/issues/113 
    - Issue is with shelljs - looks like there’s no fix version. We’d have to find an alternative

- Our ATO (Authority to Operate) mandates that we remediate high-severity vulnerabilities within 30 days

- Fractal is also used by US Web Design Standards - https://github.com/uswds/uswds#fractal

Hi there! Thanks for providing such an awesome tool. Our agency (U.S. Federal Election Commission) uses Fractal to build our pattern library (https://fec-pattern-library.app.cloud.gov/), which is a public site used to catalog our style components.

Our vulnerability tracker, Snyk, flagged Fractal’s shelljs dependency as a [high-severity command injection risk](https://snyk.io/vuln/npm:shelljs:20140723). In order to maintain our Authority to Operate (ATO), our agency is required to mitigate high-risk vulnerabilities within 30 days.

We’ve forked the repo to see if we can help explore a possible workaround https://github.com/fecgov/fractal, but it appears there is no remediation for the shelljs package dependency used in fractal, even after attempting to upgrade to the latest version. 

We’d like to know if you have any plans to address this issue with `shelljs` and if so, whether or not that would fall within our 30 day window.  If you could let us know (even if it’s just to say “we do not”), we would greatly appreciate it.

If we can help in any way with this, please let us know. Thank you for your time!

cc: @dkhuntrods and @allmarkedup

### PR DESCRIPTION
**Pull request by Chapabu**
Fixes #437 

This removes the dependency on ShellJS. We only use 3 methods, and all are relatively simple to replicate. I've added them to a utility module rather than inline in the files mainly for for testability.

Tested locally on:

* OSX High Sierra
* NodeJS 8.11.3 (NPM 5.6.0)
* NodeJS 10.8.0 (NPM 6.2.0)

### CODE REVIEW

**Comment by Chapabu** [comment]
Pausing this whilst waiting on a decision re: NodeJS 4/5 support.

**Comment by Chapabu** [comment]
Blocked by #460.

**Comment by dkhuntrods** [comment]
@Chapabu Thanks for this. I've merged #460 so this shouldn't be blocked any longer. 
I'll see if anyone in the group can test `exec` command on Windows and Linux.

**Comment by Chapabu** [comment]
How weird..this PR replaces a lib with core Node 🤔 I'll rebase from latest master and take a look!

**Comment by Chapabu** [comment]
@dkhuntrods Looks like it's passing now. May just be a funky test. If it becomes a problem again we could probably just rewrite it to check that `child_process.spawn` gets called with Sinon rather than spawning `node --version`.

**Pull request merged**
